config/routes.rb
Rails.application.routes.draw do

  get "plans/new", to: "plans#new"
  get "plans", to: "plans#index"
  post "plans", to: "plans#create"
  root "plans#new"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :category, uniqueness: { scope: [:main_group_name, :project_number, :project_name, :accuracy, :dept_name, :group_name, :sub_number, :system_name, :contract_type, :company_name, :member_rank]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  def index
    @plans = Plan.find_by_sql <<-SQL
      select
        project_number,
        project_name,
        sum(m1) as t1,
        sum(m2) as t2,
        sum(m3) as t3,
        sum(m4) as t4,
        sum(m5) as t5,
        sum(m6) as t6,
        sum(m7) as t7,
        sum(m8) as t8,
        sum(m9) as t9,
        sum(m10) as t10,
        sum(m11) as t11,
        sum(m12) as t12
      from
        plans
      group by
        project_number,
        project_name
      order by
        t1 desc
    SQL
  end

  def new
    @plan = Plan.new
  end

  PRIME_KEYS = %i(category main_group_name project_number project_name accuracy dept_name group_name sub_number system_name contract_type company_name member_rank)
  
  OTHER_KEYS = %i(unit_price manhour_last_month_landing manhour_performance manhour_development_plan manhour_landing manhour_divergence manhour_ernings money_last_month_landing money_performance money_development_plan money_landing money_divergence money_ernings cost_rate_plan cost_rate_landing gross_profit_plan gross_profit_landing gross_profit_divergence to_be_confirmed m1 m2 m3 m4 m5 m6 m7 m8 m9 m10 m11 m12)

  ALL_KEYS = PRIME_KEYS + OTHER_KEYS

  def create
    file = params[:plan][:file].path.to_s
    xlsx = Roo::Excelx.new(file)

    xlsx.each_row_streaming do |row|
      @attr = Hash[ALL_KEYS.zip(row.map(&:value))]
      @key = @attr.reject{|k,v| !PRIME_KEYS.include?(k) }
  
      next if @attr[:contract_type] =~ /合計/
      next if @attr[:contract_type] =~ /契約形態/
      next if @attr[:contract_type].nil?

      if @plan = Plan.find_by(@key)
        @plan.update(@attr)
      else
        Plan.create(@attr)
      end
    end
    @plan = Plan.new
    render :new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Uploader"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"Uploader
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

    .container
      = bootstrap_flash
      = yield

      footer
        p &copy; Company 2017

app/views/plans/_form.html.slim
= form_for @plan, html: { class: "form form-horizontal plan" } do |f|
  .form-group
    = f.label :file, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.file_field :file, :class => 'form-control'

  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), plans_path, :class => 'btn'

app/views/plans/index.html.slim
= link_to plans_new_path, class: :btn

table.table
  tr
    th 案件管理番号
    th 案件名
    th 4月
    th 5月
    th 6月
    th 7月
    th 8月
    th 9月
    th 10月
    th 11月
    th 12月
    th 1月
    th 2月
    th 3月
  - @plans.each do |plan|
      tr
        td = plan.project_number
        td = plan.project_name
        td = plan.t1&.round(2)
        td = plan.t2&.round(2)
        td = plan.t3&.round(2)
        td = plan.t4&.round(2)
        td = plan.t5&.round(2)
        td = plan.t6&.round(2)
        td = plan.t7&.round(2)
        td = plan.t8&.round(2)
        td = plan.t9&.round(2)
        td = plan.t10&.round(2)
        td = plan.t11&.round(2)
        td = plan.t12&.round(2)

app/views/plans/new.html.slim
- model_class = Plan
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"